# Generated by Django 5.1.5 on 2025-10-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRMSApp', '0002_authmodel_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('complaint_category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('complaint_files', models.ImageField(blank=True, upload_to='complaints/')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=50)),
            ],
        ),
    ]
